### ISSUE TITLE
Filename sanitization sometimes breaks GCP files

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/NodeODM#77]
If a filename is sanitized, the GCP no longer references the correct filename and will fail.

NodeODM should sanitize the GCP file as well.

**Comment by linusmartensson** [comment]
Wanted to reference https://github.com/OpenDroneMap/ODM/issues/1074 here, since this may be the same issue.
The sanitizing in NodeODM seems unnecessary since the rest of ODM works without it. In addition to the above issue, I found it causes errors when using exif files sent from a master odm instance running with --sm-cluster, and any use of the feature and match data being transferred back will also have sanitized filenames that won't match filenames in the master node.

I would think this has been missed since the two most common use cases with WebODM and CloudODM both transfer data to NodeODM at the start of processing, ensuring all filenames are mangled from the start (except GCP entries)

**Comment by pierotofy** [comment]
Sorry for the late reply, mm, I think you're right, special characters should work OK in ODM and I think this was implemented to originally fix the common issue of spaces in filenames, but since ODM handles those now, this is probably no longer needed.

**Comment by pierotofy** [comment]
Commit that introduced sanitization: https://github.com/OpenDroneMap/NodeODM/commit/cbf5e400275c08575031ea2e61cce30cfed56f03

**Comment by pierotofy** [comment]
Removed sanitization in latest master. This can be closed.
